services:
  # PostgreSQL
  db:
    build: .
    environment:
      POSTGRES_DB: app_development
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  # Golang
  back:
    build: 
      context: ./back/
      dockerfile: Dockerfile
    volumes:
      - ./back:/app
    ports:
      - "8080:8080"
    depends_on:
      - db

  # Next.js
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
    command: yarn dev -p 3000
    ports:
      - "3000:3000"
volumes:
  postgres_volume: